### ISSUE TITLE
Google

### ISSUE THREAD

**Issue by LenkaSedlackova** [VIKMSTR/chcu-parkovat#25]
je to asi citlivá a náročná téma, ale je fakt issue, že google neodpovedá na heslo "chcu parkovat v Brne". needs to be addressed, @VIKMSTR!

**Comment by VIKMSTR** [comment]
To rozhodně. SEO je slabou stránkou autora.

**Comment by VIKMSTR** [comment]
![image](https://user-images.githubusercontent.com/2676163/140606575-7f2ee9aa-139b-4937-9669-1321223d0b4d.png)
Closing.
